### ISSUE TITLE
linsert  before(after ) dong work right ，is against to redis

### ISSUE THREAD

**Issue by Ah39** [meitu/titan#10]
**titan**
![image](https://user-images.githubusercontent.com/2367243/48932799-ad547300-ef38-11e8-8436-270ce7afae70.png)

**redis**
![image](https://user-images.githubusercontent.com/2367243/48932813-bd6c5280-ef38-11e8-8fc4-c97b8707e67e.png)
version
# Server
titan_version:
titan_git_sha1:c3b75af

**Comment by shafreeck** [comment]
Yes,  it is a bug, we are going to fix it. Thanks a lot for you feedback.

**Comment by shafreeck** [comment]
Fixed https://github.com/meitu/titan/commit/63f480794973988b134ecab8ae0cdb30e60b3c2b. Would you like to try again ?
