### ISSUE TITLE
titan和redis比较的优缺点是？

### ISSUE THREAD

**Issue by xrfinbupt** [meitu/titan#14]
什么场景下使用titan会更好

**Comment by shafreeck** [comment]
其实Titan覆盖的场景， 应该是Redis覆盖不掉的场景。Titan 和 Redis 虽然是相同的协议，但是要解决的场景完全不同。

如果使用Redis没有什么痛点，就完全不需要迁移到Titan。那么Titan的特点的话， 主要有两个
1. 高可用可扩展， 这个特点决定了，数据量要足够大才合适，数据量增长快的话，我们知道Redis扩容困难，那么Titan就可以平滑扩容， 并且相比Redis，Titan 是容忍少数节点挂掉的。Redis在主节点挂掉时，有丢数据的风险。
2. 分布式事务， 这个是业务本身有事务的需求，但因为数据量大，导致数据分布式存储，如果用MySQL分库分表或者Redis分端口的方式，都没法直接用分布式事务（可能需要引入中间件），这种场景Titan就比较合适
