### ISSUE TITLE
lpush is  slow ？

### ISSUE THREAD

**Issue by Ah39** [meitu/titan#15]
redis-benchmark 1 connection lpush the qps is smaller than 100，99.99% Latency  is more than 100ms

**Comment by arthurkiller** [comment]
Have you checked your environment yet?Benchmark your TiKV and put up more evidence here.

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by shafreeck** [comment]
It does not perform well on a single list, because of the transaction conflicts of TiKV. @arthurkiller Would you like to explain the problem more to @Ah39 ?

**Comment by Ah39** [comment]
yes is is A single list, but only 1 connection push to the list , the qps is smaller too

**Comment by shafreeck** [comment]
@Ah39 Yes, it is slow to write a single list. Try to use `__rand_int__` to generate multiple keys?

**Comment by shafreeck** [comment]
@Ah39 Also, you can use `fperf` to run benchmarks which gives more details. https://github.com/fperf/redis

**Comment by arthurkiller** [comment]
@Ah39 There are may possible factors can cause performance down.

* Once you request to modify(write) a list concurrently, it will cause to conflicts and failures.
* Tikv performance rely on hardware, u'd better performance your environment before use. 

You can put up your benchmark results and platform informations.
