### ISSUE TITLE
我看readme里写到支持多租户，如何配置呢？

### ISSUE THREAD

**Issue by shikui** [meitu/titan#16]
只有一个与redis兼容的auth指令，没有找到配置多租户的地方。

**Comment by arthurkiller** [comment]
That’s is

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by shikui** [comment]
明白了，多谢

**Comment by dolfly** [comment]
> 如果你不介意，可以发我微信，我把你拉到titan交流群里。

能否拉我仅titan交流群里

**Comment by shafreeck** [comment]
@dolfly 没问题， 微信发到我的邮箱吧 shafreeck@gmail.com

**Comment by shafreeck** [comment]
Added to document https://github.com/meitu/titan/pull/18
