### ISSUE TITLE
Scripting atomicity

### ISSUE THREAD

**Issue by ssoroka** [meitu/titan#2]
Very interesting!
One of the key features I liked about redis is that scripts were executed atomically; there was no chance that another command was executed in between a group of commands in a script. Is there any plan to support this, or are there plans to deviate from Redis in some ways, such as this? If so, it’d be good to start documenting these deviations.

**Comment by arthurkiller** [comment]
awesome！

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by shafreeck** [comment]
@ssoroka Scripting is a great feature of Redis and we indeed plan to support it. However, the project is young and there many foundation features(Ex. hashes, sorted set ...) are missing now. We are going to support these more common features first.

If scripting is an urgent requirement for you, feel free to submit a pull request, and let's make the project more mature together.

**Comment by shafreeck** [comment]
I closed the issue, feel free to reopen it if necessary.
