### ISSUE TITLE
key differences to https://github.com/yongman/tidis ?

### ISSUE THREAD

**Issue by gedw99** [meitu/titan#4]
If you know the differences it would be great ..

**Comment by arthurkiller** [comment]
This repo has totally different design about how to implement redis data structure. The key point is high performance and easy using.

You will find the difference after the benchmark.

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by shafreeck** [comment]
I don’t know much about Tidis before. AFAIK,  Titan and Tidis are all Redis prototocol layer based on TiKV. However, Titan is built to solve our reality requirements inside Meitu, so we built it with production suitable and Redis completely compatible keeping in mind.

We did a lot of work to solve the real problems we occurred, like how to delete a large list, how to import data with high performance, etc.

I can not give you a complete compare between Titan and Tidis, so I list some difference I noticed so far.

## Non-block on deleting large objects
* Titan uses a GC strategy to delete a large data structure like List, Hash, or Set, there is no block at all. 
* Tidis will block the subsequent requests for the same list which is deleting.

## Supporting insert or remove of a list
* Titan designs List with all features support, like inserting or removing items
* Titan can not support linsert and lrem commands.

## Multi-tenancy support
* Titan can share with multiple users with data isolation in one cluster, all the user seems like using a separate Redis cluster.
* Tidis does not have this feature

## Special designs to improve the performance to import data
* We create a ziplist when importing data, to avoid the write amplification(Tidis also has this problem in design)
* Tidis no not improve this.

After all, Titan is a completely different implementation though they have the same goal and technology stack.

**Comment by gedw99** [comment]
@shafreeck @arthurkiller thanks for the excellent comparison !!
It might be good practice to add the comparison to a .md page somewhere. Makes it easy for devs to see what it is.

**Comment by stormltf** [comment]
hehe

**Comment by shafreeck** [comment]
@gedw99 Thanks for your advice. I am going to add a link refer to this issue
